// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// rpm_counter //
// ----------- //

#define rpm_counter_wrap_target 0
#define rpm_counter_wrap 3
#define rpm_counter_pio_version 0

static const uint16_t rpm_counter_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0                   
    0x2020, //  1: wait   0 pin, 0                   
    0x0041, //  2: jmp    x--, 1                     
    0xc020, //  3: irq    wait 0                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rpm_counter_program = {
    .instructions = rpm_counter_program_instructions,
    .length = 4,
    .origin = -1,
    //.pio_version = rpm_counter_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rpm_counter_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rpm_counter_wrap_target, offset + rpm_counter_wrap);
    return c;
}
#endif

